POST http://localhost:3000/books/
Content-Type: application/json

{
  "title": "Game of Thrones", 
  "author": "George RR Martin", 
  "description": "Dragons n shit", 
  "price": 1
}

###

// === All authors/books ===
GET http://localhost:3000/author

Content-Type: application/json

{
  "name": "Rebecca Yarros",
  "books": "Fourth Wing"
}