POST http://localhost:3000/books/
Content-Type: application/json

{
  "title": "Game of Thrones", 
  "author": "George RR Martin", 
  "description": "Dragons n shit", 
  "price": 1,
  "isbn": "ISBN: 9780553381689"
}


###
POST http://localhost:3000/books/
Content-Type: application/json

{
  "title": "Fourth Wing", 
  "author": "Rebecca Yarros", 
  "description": "Girl and her dragon", 
  "price": 3,
  "isbn": "9789129710987",
  "imageUrl": "https://m.media-amazon.com/images/I/91n7p-j5aqL._AC_UF894,1000_QL80_.jpg"
}
###
DELETE http://localhost:3000/books/
Content-Type: application/json

{
"bookId": "6502cd810fa611a64280e771"
}

###
PUT http://localhost:3000/books/ 
Content-Type: application/json

{
"bookId": "6502cedcf5d14dd57a7f1e1d",
"title": "Pippi på äventyr 2",
"author": "Astrid Lindgren",
"description": "Pippi på äventyr",
"price": 14.99
}

###
//Order Requests
POST http://localhost:3000/orders/
Content-Type: application/json

{
  "firstName": "Albin", 
  "lastName": "Jönsson",
  "address": { "zip": "54843", "streetAddress": "Albins väg 12A", "city": "Borås" },
  "phoneNumber": "070584697",
  "email": "Albin@live.se",
  "books": ["6502cedcf5d14dd57a7f1e1d"
],
  "totalPrice": 11,
  "shippingMethod": "Express",
  "paymentMethod": "Swish"
  
}
###
PUT http://localhost:3000/orders/
Content-Type: application/json

{
  "orderId": "65041559235e81dd44c8c2a2",  
  "status": "Under Transportation"  
}

###

// === All authors  ===
GET http://localhost:3000/author

Content-Type: application/json


### book by id

GET http://localhost:3000/books/65042650856c7167ec39377b

### get Astrid Lindgren books
GET http://localhost:3000/author/65116dab4695bbe3b12244a7/books
